---

- hosts: bastion
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

#    - community.crypto.openssh_keypair:
#        path: ./k3s_id_rsa
#        comment: k3s
#        size: 4096
#        state: present
#        type: rsa
#      delegate_to: 127.0.0.1

  roles:
    - ckaserer.authorized_keys
    - ckaserer.k3s_bastion
    - gepardec.k3s_iptables
    - ckaserer.dhcp
    - bertvv.bind
    - gepardec.k3s_haproxy

...
